### ISSUE TITLE
[Frontend] Navbar

### ISSUE THREAD

**Issue by kevink856** [cses-webdev-main/MainWebsite#20]
(Use the hi-fi designs for each respective component / page on MainWebsite-Documentation.)

Implement the following:
- Make links color #5780BB when hovered
- Make all components scaled with screen size (vh, vw), keep them looking similar to hi-fi design on any size
- Fix CSS of all pages to match "Home"

Refer to [Style Guide](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Style%20Guide.png) for any formatting.

**Comment by angelatsai1214** [comment]
Can you clarify on the third bullet pt?

**Comment by kevink856** [comment]
Sure, if you click the different links Home / the landing page will visibly have slightly different styling than the others. Home's is correct and the rest need to match it and whatever other changes you make to it

**Comment by angelatsai1214** [comment]
The font size i think is adjusted in each page!
