### ISSUE TITLE
[Frontend] Media Page

### ISSUE THREAD

**Issue by kevink856** [cses-webdev-main/MainWebsite#25]
(Use the hi-fi designs for each respective component / page on MainWebsite-Documentation.)

Implement the following:
- Make Calendar just a box shaped correctly as shown on design for now
- Make all media images links, and replace Twitter with Discord
- (you can find all relevant links in "Footer")

See design [here](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Media%20Page%20Hi-Fi.png).
Refer to [Style Guide](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Style%20Guide.png) for any formatting.

**Comment by angelatsai1214** [comment]
![Image](https://github.com/cses-webdev-main/MainWebsite/assets/64194102/d46f802b-951c-4fef-b9e8-5a4d83af7ef0)
