### ISSUE TITLE
[Frontend] Home Page

### ISSUE THREAD

**Issue by kevink856** [cses-webdev-main/MainWebsite#29]
(Use the hi-fi designs for each respective component / page on MainWebsite-Documentation.)

Implement the following:
- Make all components scaled with screen size (vh, vw), keep them looking similar to hi-fi design on any size (it's ok if row-aligned spills over to column-aligned)
- "Apply" button's link is [this](https://docs.google.com/forms/d/e/1FAIpQLSd578y6E_BOvy9HRRJiW0lxNF4wl_4QW5DaqpTfrQ9Uo3rl7w/viewform)
- You can find all relevant images and backgrounds in "home_images" on MainWebsite-Documentation
- Make sure to refer to "Style Guide.png" for which font weights to use for which texts

See design [here](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Home_Page_Hi-Fi.png).
Refer to [Style Guide](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Style%20Guide.png) for any formatting.

**Comment by angelatsai1214** [comment]
Mostly done, except for the font weights and font family styling that still need to be fixed (though atm the webpage look very similar to the ho-fi design already)

**Comment by angelatsai1214** [comment]
TODO: 
- Match font and font size to the design
- Need to adjust the image border as necessarily bc currently it's in "em" which is dependant of font size as far as I know
- Also need to adjust icon size in the second section
- Adjust footer icon size as well.
