### ISSUE TITLE
[Frontend] About Us Page

### ISSUE THREAD

**Issue by kevink856** [cses-webdev-main/MainWebsite#30]
(Use the hi-fi designs for each respective component / page on MainWebsite-Documentation.)

Implement the following:
- Make all components scaled with screen size (vh, vw), keep them looking similar to hi-fi design on any size (it's ok if row-aligned spills over to column-aligned)
- Make the LinkedIn and IG images links, but just direct to nothing for now
- You can find each board members' images on LinkedIn
- You can find all relevant images and backgrounds in "home_images" on MainWebsite-Documentation
- Make sure to refer to "Style Guide.png" for which font weights to use for which texts

See design [here](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/About_Us_Hi-Fi.png).
Refer to [Style Guide](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Style%20Guide.png) for any formatting.

**Comment by angelatsai1214** [comment]
TODO: 

- Match font and font size to the design
- Adjust the size for the footer as well to match the design 
- Update the Board section correctly to match the design when we get all the necessarily info
           > for the icon, check Media.js (basically import FaInstagram and FaLinkedinIn icons and then use Link tag and the imported icon
