### ISSUE TITLE
[Frontend] Footer

### ISSUE THREAD

**Issue by kevink856** [cses-webdev-main/MainWebsite#31]
(Use the hi-fi designs for each respective component / page on MainWebsite-Documentation.)

Implement the following:
- Replace link placeholders (LI, IG, etc.) with their respectives logo images
- Make all components scaled with screen size (vh, vw), keep them looking similar to hi-fi design on any size
- Add "Footer" component to the bottom of every page ("Home" page is already done for you so you can use it as a reference)

Refer to [Style Guide](https://github.com/cses-webdev-main/MainWebsite-Documentation/blob/main/UX-UI/Hi-Fi/Style%20Guide.png) for any formatting.

**Comment by angelatsai1214** [comment]
Replaced the logo.
